import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bookmark,
  BookOpen,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleHelp,
  CirclePlay,
  Clock3,
  Construction,
  Copy,
  Drill,
  FileText,
  FolderOpen,
  GitCompareArrows,
  Hammer,
  Heart,
  House,
  ImageOff,
  Info,
  LayoutGrid,
  ListPlus,
  Layers3,
  MessageCircle,
  Menu,
  Package,
  PackageOpen,
  PackageX,
  PhoneCall,
  Phone,
  PlugZap,
  Ruler,
  RefreshCw,
  Search,
  Send,
  Share2,
  SlidersHorizontal,
  Sparkles,
  Trash2,
  TriangleAlert,
  WifiOff,
  Wrench,
  X,
  Zap,
  ZoomIn,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

const ICONS = {
  alert: TriangleAlert,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  bookmark: Bookmark,
  bookOpen: BookOpen,
  check: Check,
  checkCircle: CircleCheck,
  helpCircle: CircleHelp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock3,
  construction: Construction,
  copy: Copy,
  drill: Drill,
  fileText: FileText,
  folder: FolderOpen,
  gitCompare: GitCompareArrows,
  grid: LayoutGrid,
  hammer: Hammer,
  heart: Heart,
  home: House,
  imageOff: ImageOff,
  info: Info,
  layers: Layers3,
  listPlus: ListPlus,
  message: MessageCircle,
  menu: Menu,
  package: Package,
  packageOpen: PackageOpen,
  packageX: PackageX,
  phone: Phone,
  phoneCall: PhoneCall,
  play: CirclePlay,
  plugZap: PlugZap,
  ruler: Ruler,
  refreshCw: RefreshCw,
  search: Search,
  send: Send,
  share: Share2,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  trash: Trash2,
  wifiOff: WifiOff,
  wrench: Wrench,
  x: X,
  zap: Zap,
  zoomIn: ZoomIn,
} as const satisfies Record<string, LucideIcon>;

export type UiIconName = keyof typeof ICONS;

interface UiIconProps extends LucideProps {
  name: UiIconName;
}

/** The only visual icon set used by the Mini App: Lucide line icons. */
export const UiIcon = ({ name, size = 24, strokeWidth = 1.9, ...props }: UiIconProps) => {
  const Icon = ICONS[name];
  return <Icon aria-hidden="true" size={size} strokeWidth={strokeWidth} {...props} />;
};
